/*
* This header is generated by classdump-dyld 1.0
* on Sunday, November 10, 2019 at 11:50:43 PM Eastern European Standard Time
* Operating System: Version 13.1.3 (Build 17A878)
* Image Source: /System/Library/PrivateFrameworks/SystemStatusServer.framework/SystemStatusServer
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct __CTServerConnection* CTServerConnectionRef;

typedef struct {
	int field1;
	int field2;
} SCD_Struct_ST2;
